#pragma once

#include <JuceHeader.h>
#include "../render/SampleClock.h"
#include <array>
#include <atomic>
#include <limits>
#include <new>

namespace motion {
// Shared synchronous worker writer. Samples are generated by exact integer
// frame index; only a flushed, header-verified temporary file replaces output.
class WavExporter {
public:
    template <std::size_t Channels, typename Sampler>
    static juce::Result write(double duration, const juce::File& destination, double sampleRate, const std::atomic<bool>& cancel, std::atomic<double>* progress, Sampler sample, juce::String label, juce::String nonFiniteError) try {
        static_assert(Channels > 0 && Channels <= 64);
        if (progress != nullptr) {
            progress->store(0.0, std::memory_order_relaxed);
        }
        if (cancel.load(std::memory_order_relaxed)) {
            return juce::Result::fail(label + " export cancelled.");
        }
        constexpr auto bytesPerFrame = Channels * sizeof(float);
        if (!std::isfinite(sampleRate) || sampleRate <= 0.0 || sampleRate != std::floor(sampleRate)
            || sampleRate > static_cast<double>(std::numeric_limits<std::uint32_t>::max() / bytesPerFrame)) {
            return juce::Result::fail("Choose a positive whole-number sample rate that fits the WAV format (for example, 48000 Hz).");
        }
        // Integer sample indices must remain exact when converted to the double
        // clock, and the encoded file size must fit signed file offsets.
        const auto frameCount = sampleIndex(duration, sampleRate);
        if (!frameCount.has_value() || *frameCount < 1) {
            return juce::Result::fail("Choose a finite positive composition duration that produces at least one sample and fits the export sample clock.");
        }
        if (destination == juce::File() || destination.isDirectory() || !destination.getParentDirectory().isDirectory()) {
            return juce::Result::fail("Choose a WAV file in an existing destination folder.");
        }
        const auto sampleCount = *frameCount;
        const auto frames = static_cast<double>(sampleCount);
        juce::TemporaryFile pending(destination);
        {
            // Keep the file stream alive after the writer has finalized its
            // header so destructor-time write failures are observable.
            juce::FileOutputStream fileStream(pending.getFile());
            if (!fileStream.openedOk()) {
                return juce::Result::fail("Cannot create the temporary WAV beside the destination: " + fileStream.getStatus().getErrorMessage());
            }
            std::unique_ptr<juce::OutputStream> output = std::make_unique<BorrowedOutputStream>(fileStream);
            juce::WavAudioFormat format;
            const auto options = juce::AudioFormatWriterOptions().withSampleRate(sampleRate).withChannelLayout(juce::AudioChannelSet::discreteChannels(static_cast<int>(Channels)))
                .withBitsPerSample(32).withSampleFormat(juce::AudioFormatWriterOptions::SampleFormat::floatingPoint);
            auto writer = format.createWriterFor(output, options);
            if (writer == nullptr) {
                return juce::Result::fail("Cannot create the " + juce::String(static_cast<int>(Channels)) + "-channel floating-point WAV writer at the selected sample rate.");
            }
            constexpr int blockSize = 4096;
            juce::AudioBuffer<float> buffer(static_cast<int>(Channels), blockSize);
            for (juce::int64 first = 0; first < sampleCount; first += blockSize) {
                const auto count = static_cast<int>(std::min<juce::int64>(blockSize, sampleCount - first));
                for (int offset = 0; offset < count; ++offset) {
                    if ((offset & 255) == 0 && cancel.load(std::memory_order_relaxed)) {
                        return juce::Result::fail(label + " export cancelled.");
                    }
                    const auto index = static_cast<double>(first + offset);
                    const auto time = index / sampleRate;
                    const std::array<float, Channels> channels = sample(index, time);
                    for (int channel = 0; channel < static_cast<int>(Channels); ++channel) {
                        if (!std::isfinite(channels[static_cast<std::size_t>(channel)])) {
                            return juce::Result::fail(nonFiniteError);
                        }
                        buffer.setSample(channel, offset, channels[static_cast<std::size_t>(channel)]);
                    }
                }
                if (!writer->writeFromAudioSampleBuffer(buffer, 0, count)) {
                    return juce::Result::fail("Cannot write the WAV audio. Check destination permissions and available disk space.");
                }
                if (progress != nullptr) {
                    progress->store(0.99 * static_cast<double>(first + count) / frames, std::memory_order_relaxed);
                }
            }
            const bool writerFlushed = writer->flush();
            writer.reset();
            fileStream.flush();
            if (!writerFlushed || fileStream.getStatus().failed()) {
                return juce::Result::fail("Cannot finalize the WAV audio. Check destination permissions and available disk space.");
            }
        }
        if (cancel.load(std::memory_order_relaxed)) {
            return juce::Result::fail(label + " export cancelled.");
        }
        {
            juce::WavAudioFormat format;
            auto input = pending.getFile().createInputStream();
            if (input == nullptr) {
                return juce::Result::fail("Cannot reopen the completed temporary WAV for verification; the destination was left unchanged.");
            }
            std::unique_ptr<juce::AudioFormatReader> reader(format.createReaderFor(input.release(), true));
            if (reader == nullptr || reader->numChannels != Channels || reader->bitsPerSample != 32 || !reader->usesFloatingPointData
                || reader->lengthInSamples != sampleCount || reader->sampleRate != sampleRate) {
                return juce::Result::fail("The completed WAV could not be verified; the destination was left unchanged.");
            }
        }
        if (cancel.load(std::memory_order_relaxed)) {
            return juce::Result::fail(label + " export cancelled.");
        }
        if (!pending.overwriteTargetFileWithTemporary()) {
            return juce::Result::fail("Cannot replace the destination WAV. Close applications using it and check folder permissions.");
        }
        if (progress != nullptr) {
            progress->store(1.0, std::memory_order_relaxed);
        }
        return juce::Result::ok();
    } catch (const std::bad_alloc&) {
        return juce::Result::fail("Not enough memory to export the WAV.");
    } catch (...) {
        return juce::Result::fail("WAV export failed while preparing or writing samples. The destination was not replaced.");
    }

private:
    class BorrowedOutputStream final : public juce::OutputStream {
    public:
        explicit BorrowedOutputStream(juce::FileOutputStream& stream) : stream(stream) {}
        void flush() override { stream.flush(); }
        bool setPosition(juce::int64 position) override { return stream.setPosition(position); }
        juce::int64 getPosition() override { return stream.getPosition(); }
        bool write(const void* data, std::size_t size) override { return stream.write(data, size); }

    private:
        juce::FileOutputStream& stream;
    };

};
}
