Swizzle<T, Dim, Packed, 0, 0> xx;
Swizzle<T, Dim, Packed, 0, 1> xy;
Swizzle<T, Dim, Packed, 0, 2> xz;
Swizzle<T, Dim, Packed, 0, 3> xw;
Swizzle<T, Dim, Packed, 1, 0> yx;
Swizzle<T, Dim, Packed, 1, 1> yy;
Swizzle<T, Dim, Packed, 1, 2> yz;
Swizzle<T, Dim, Packed, 1, 3> yw;
Swizzle<T, Dim, Packed, 2, 0> zx;
Swizzle<T, Dim, Packed, 2, 1> zy;
Swizzle<T, Dim, Packed, 2, 2> zz;
Swizzle<T, Dim, Packed, 2, 3> zw;
Swizzle<T, Dim, Packed, 3, 0> wx;
Swizzle<T, Dim, Packed, 3, 1> wy;
Swizzle<T, Dim, Packed, 3, 2> wz;
Swizzle<T, Dim, Packed, 3, 3> ww;
Swizzle<T, Dim, Packed, 0, 0, 0> xxx;
Swizzle<T, Dim, Packed, 0, 0, 1> xxy;
Swizzle<T, Dim, Packed, 0, 0, 2> xxz;
Swizzle<T, Dim, Packed, 0, 0, 3> xxw;
Swizzle<T, Dim, Packed, 0, 1, 0> xyx;
Swizzle<T, Dim, Packed, 0, 1, 1> xyy;
Swizzle<T, Dim, Packed, 0, 1, 2> xyz;
Swizzle<T, Dim, Packed, 0, 1, 3> xyw;
Swizzle<T, Dim, Packed, 0, 2, 0> xzx;
Swizzle<T, Dim, Packed, 0, 2, 1> xzy;
Swizzle<T, Dim, Packed, 0, 2, 2> xzz;
Swizzle<T, Dim, Packed, 0, 2, 3> xzw;
Swizzle<T, Dim, Packed, 0, 3, 0> xwx;
Swizzle<T, Dim, Packed, 0, 3, 1> xwy;
Swizzle<T, Dim, Packed, 0, 3, 2> xwz;
Swizzle<T, Dim, Packed, 0, 3, 3> xww;
Swizzle<T, Dim, Packed, 1, 0, 0> yxx;
Swizzle<T, Dim, Packed, 1, 0, 1> yxy;
Swizzle<T, Dim, Packed, 1, 0, 2> yxz;
Swizzle<T, Dim, Packed, 1, 0, 3> yxw;
Swizzle<T, Dim, Packed, 1, 1, 0> yyx;
Swizzle<T, Dim, Packed, 1, 1, 1> yyy;
Swizzle<T, Dim, Packed, 1, 1, 2> yyz;
Swizzle<T, Dim, Packed, 1, 1, 3> yyw;
Swizzle<T, Dim, Packed, 1, 2, 0> yzx;
Swizzle<T, Dim, Packed, 1, 2, 1> yzy;
Swizzle<T, Dim, Packed, 1, 2, 2> yzz;
Swizzle<T, Dim, Packed, 1, 2, 3> yzw;
Swizzle<T, Dim, Packed, 1, 3, 0> ywx;
Swizzle<T, Dim, Packed, 1, 3, 1> ywy;
Swizzle<T, Dim, Packed, 1, 3, 2> ywz;
Swizzle<T, Dim, Packed, 1, 3, 3> yww;
Swizzle<T, Dim, Packed, 2, 0, 0> zxx;
Swizzle<T, Dim, Packed, 2, 0, 1> zxy;
Swizzle<T, Dim, Packed, 2, 0, 2> zxz;
Swizzle<T, Dim, Packed, 2, 0, 3> zxw;
Swizzle<T, Dim, Packed, 2, 1, 0> zyx;
Swizzle<T, Dim, Packed, 2, 1, 1> zyy;
Swizzle<T, Dim, Packed, 2, 1, 2> zyz;
Swizzle<T, Dim, Packed, 2, 1, 3> zyw;
Swizzle<T, Dim, Packed, 2, 2, 0> zzx;
Swizzle<T, Dim, Packed, 2, 2, 1> zzy;
Swizzle<T, Dim, Packed, 2, 2, 2> zzz;
Swizzle<T, Dim, Packed, 2, 2, 3> zzw;
Swizzle<T, Dim, Packed, 2, 3, 0> zwx;
Swizzle<T, Dim, Packed, 2, 3, 1> zwy;
Swizzle<T, Dim, Packed, 2, 3, 2> zwz;
Swizzle<T, Dim, Packed, 2, 3, 3> zww;
Swizzle<T, Dim, Packed, 3, 0, 0> wxx;
Swizzle<T, Dim, Packed, 3, 0, 1> wxy;
Swizzle<T, Dim, Packed, 3, 0, 2> wxz;
Swizzle<T, Dim, Packed, 3, 0, 3> wxw;
Swizzle<T, Dim, Packed, 3, 1, 0> wyx;
Swizzle<T, Dim, Packed, 3, 1, 1> wyy;
Swizzle<T, Dim, Packed, 3, 1, 2> wyz;
Swizzle<T, Dim, Packed, 3, 1, 3> wyw;
Swizzle<T, Dim, Packed, 3, 2, 0> wzx;
Swizzle<T, Dim, Packed, 3, 2, 1> wzy;
Swizzle<T, Dim, Packed, 3, 2, 2> wzz;
Swizzle<T, Dim, Packed, 3, 2, 3> wzw;
Swizzle<T, Dim, Packed, 3, 3, 0> wwx;
Swizzle<T, Dim, Packed, 3, 3, 1> wwy;
Swizzle<T, Dim, Packed, 3, 3, 2> wwz;
Swizzle<T, Dim, Packed, 3, 3, 3> www;
Swizzle<T, Dim, Packed, 0, 0, 0, 0> xxxx;
Swizzle<T, Dim, Packed, 0, 0, 0, 1> xxxy;
Swizzle<T, Dim, Packed, 0, 0, 0, 2> xxxz;
Swizzle<T, Dim, Packed, 0, 0, 0, 3> xxxw;
Swizzle<T, Dim, Packed, 0, 0, 1, 0> xxyx;
Swizzle<T, Dim, Packed, 0, 0, 1, 1> xxyy;
Swizzle<T, Dim, Packed, 0, 0, 1, 2> xxyz;
Swizzle<T, Dim, Packed, 0, 0, 1, 3> xxyw;
Swizzle<T, Dim, Packed, 0, 0, 2, 0> xxzx;
Swizzle<T, Dim, Packed, 0, 0, 2, 1> xxzy;
Swizzle<T, Dim, Packed, 0, 0, 2, 2> xxzz;
Swizzle<T, Dim, Packed, 0, 0, 2, 3> xxzw;
Swizzle<T, Dim, Packed, 0, 0, 3, 0> xxwx;
Swizzle<T, Dim, Packed, 0, 0, 3, 1> xxwy;
Swizzle<T, Dim, Packed, 0, 0, 3, 2> xxwz;
Swizzle<T, Dim, Packed, 0, 0, 3, 3> xxww;
Swizzle<T, Dim, Packed, 0, 1, 0, 0> xyxx;
Swizzle<T, Dim, Packed, 0, 1, 0, 1> xyxy;
Swizzle<T, Dim, Packed, 0, 1, 0, 2> xyxz;
Swizzle<T, Dim, Packed, 0, 1, 0, 3> xyxw;
Swizzle<T, Dim, Packed, 0, 1, 1, 0> xyyx;
Swizzle<T, Dim, Packed, 0, 1, 1, 1> xyyy;
Swizzle<T, Dim, Packed, 0, 1, 1, 2> xyyz;
Swizzle<T, Dim, Packed, 0, 1, 1, 3> xyyw;
Swizzle<T, Dim, Packed, 0, 1, 2, 0> xyzx;
Swizzle<T, Dim, Packed, 0, 1, 2, 1> xyzy;
Swizzle<T, Dim, Packed, 0, 1, 2, 2> xyzz;
Swizzle<T, Dim, Packed, 0, 1, 2, 3> xyzw;
Swizzle<T, Dim, Packed, 0, 1, 3, 0> xywx;
Swizzle<T, Dim, Packed, 0, 1, 3, 1> xywy;
Swizzle<T, Dim, Packed, 0, 1, 3, 2> xywz;
Swizzle<T, Dim, Packed, 0, 1, 3, 3> xyww;
Swizzle<T, Dim, Packed, 0, 2, 0, 0> xzxx;
Swizzle<T, Dim, Packed, 0, 2, 0, 1> xzxy;
Swizzle<T, Dim, Packed, 0, 2, 0, 2> xzxz;
Swizzle<T, Dim, Packed, 0, 2, 0, 3> xzxw;
Swizzle<T, Dim, Packed, 0, 2, 1, 0> xzyx;
Swizzle<T, Dim, Packed, 0, 2, 1, 1> xzyy;
Swizzle<T, Dim, Packed, 0, 2, 1, 2> xzyz;
Swizzle<T, Dim, Packed, 0, 2, 1, 3> xzyw;
Swizzle<T, Dim, Packed, 0, 2, 2, 0> xzzx;
Swizzle<T, Dim, Packed, 0, 2, 2, 1> xzzy;
Swizzle<T, Dim, Packed, 0, 2, 2, 2> xzzz;
Swizzle<T, Dim, Packed, 0, 2, 2, 3> xzzw;
Swizzle<T, Dim, Packed, 0, 2, 3, 0> xzwx;
Swizzle<T, Dim, Packed, 0, 2, 3, 1> xzwy;
Swizzle<T, Dim, Packed, 0, 2, 3, 2> xzwz;
Swizzle<T, Dim, Packed, 0, 2, 3, 3> xzww;
Swizzle<T, Dim, Packed, 0, 3, 0, 0> xwxx;
Swizzle<T, Dim, Packed, 0, 3, 0, 1> xwxy;
Swizzle<T, Dim, Packed, 0, 3, 0, 2> xwxz;
Swizzle<T, Dim, Packed, 0, 3, 0, 3> xwxw;
Swizzle<T, Dim, Packed, 0, 3, 1, 0> xwyx;
Swizzle<T, Dim, Packed, 0, 3, 1, 1> xwyy;
Swizzle<T, Dim, Packed, 0, 3, 1, 2> xwyz;
Swizzle<T, Dim, Packed, 0, 3, 1, 3> xwyw;
Swizzle<T, Dim, Packed, 0, 3, 2, 0> xwzx;
Swizzle<T, Dim, Packed, 0, 3, 2, 1> xwzy;
Swizzle<T, Dim, Packed, 0, 3, 2, 2> xwzz;
Swizzle<T, Dim, Packed, 0, 3, 2, 3> xwzw;
Swizzle<T, Dim, Packed, 0, 3, 3, 0> xwwx;
Swizzle<T, Dim, Packed, 0, 3, 3, 1> xwwy;
Swizzle<T, Dim, Packed, 0, 3, 3, 2> xwwz;
Swizzle<T, Dim, Packed, 0, 3, 3, 3> xwww;
Swizzle<T, Dim, Packed, 1, 0, 0, 0> yxxx;
Swizzle<T, Dim, Packed, 1, 0, 0, 1> yxxy;
Swizzle<T, Dim, Packed, 1, 0, 0, 2> yxxz;
Swizzle<T, Dim, Packed, 1, 0, 0, 3> yxxw;
Swizzle<T, Dim, Packed, 1, 0, 1, 0> yxyx;
Swizzle<T, Dim, Packed, 1, 0, 1, 1> yxyy;
Swizzle<T, Dim, Packed, 1, 0, 1, 2> yxyz;
Swizzle<T, Dim, Packed, 1, 0, 1, 3> yxyw;
Swizzle<T, Dim, Packed, 1, 0, 2, 0> yxzx;
Swizzle<T, Dim, Packed, 1, 0, 2, 1> yxzy;
Swizzle<T, Dim, Packed, 1, 0, 2, 2> yxzz;
Swizzle<T, Dim, Packed, 1, 0, 2, 3> yxzw;
Swizzle<T, Dim, Packed, 1, 0, 3, 0> yxwx;
Swizzle<T, Dim, Packed, 1, 0, 3, 1> yxwy;
Swizzle<T, Dim, Packed, 1, 0, 3, 2> yxwz;
Swizzle<T, Dim, Packed, 1, 0, 3, 3> yxww;
Swizzle<T, Dim, Packed, 1, 1, 0, 0> yyxx;
Swizzle<T, Dim, Packed, 1, 1, 0, 1> yyxy;
Swizzle<T, Dim, Packed, 1, 1, 0, 2> yyxz;
Swizzle<T, Dim, Packed, 1, 1, 0, 3> yyxw;
Swizzle<T, Dim, Packed, 1, 1, 1, 0> yyyx;
Swizzle<T, Dim, Packed, 1, 1, 1, 1> yyyy;
Swizzle<T, Dim, Packed, 1, 1, 1, 2> yyyz;
Swizzle<T, Dim, Packed, 1, 1, 1, 3> yyyw;
Swizzle<T, Dim, Packed, 1, 1, 2, 0> yyzx;
Swizzle<T, Dim, Packed, 1, 1, 2, 1> yyzy;
Swizzle<T, Dim, Packed, 1, 1, 2, 2> yyzz;
Swizzle<T, Dim, Packed, 1, 1, 2, 3> yyzw;
Swizzle<T, Dim, Packed, 1, 1, 3, 0> yywx;
Swizzle<T, Dim, Packed, 1, 1, 3, 1> yywy;
Swizzle<T, Dim, Packed, 1, 1, 3, 2> yywz;
Swizzle<T, Dim, Packed, 1, 1, 3, 3> yyww;
Swizzle<T, Dim, Packed, 1, 2, 0, 0> yzxx;
Swizzle<T, Dim, Packed, 1, 2, 0, 1> yzxy;
Swizzle<T, Dim, Packed, 1, 2, 0, 2> yzxz;
Swizzle<T, Dim, Packed, 1, 2, 0, 3> yzxw;
Swizzle<T, Dim, Packed, 1, 2, 1, 0> yzyx;
Swizzle<T, Dim, Packed, 1, 2, 1, 1> yzyy;
Swizzle<T, Dim, Packed, 1, 2, 1, 2> yzyz;
Swizzle<T, Dim, Packed, 1, 2, 1, 3> yzyw;
Swizzle<T, Dim, Packed, 1, 2, 2, 0> yzzx;
Swizzle<T, Dim, Packed, 1, 2, 2, 1> yzzy;
Swizzle<T, Dim, Packed, 1, 2, 2, 2> yzzz;
Swizzle<T, Dim, Packed, 1, 2, 2, 3> yzzw;
Swizzle<T, Dim, Packed, 1, 2, 3, 0> yzwx;
Swizzle<T, Dim, Packed, 1, 2, 3, 1> yzwy;
Swizzle<T, Dim, Packed, 1, 2, 3, 2> yzwz;
Swizzle<T, Dim, Packed, 1, 2, 3, 3> yzww;
Swizzle<T, Dim, Packed, 1, 3, 0, 0> ywxx;
Swizzle<T, Dim, Packed, 1, 3, 0, 1> ywxy;
Swizzle<T, Dim, Packed, 1, 3, 0, 2> ywxz;
Swizzle<T, Dim, Packed, 1, 3, 0, 3> ywxw;
Swizzle<T, Dim, Packed, 1, 3, 1, 0> ywyx;
Swizzle<T, Dim, Packed, 1, 3, 1, 1> ywyy;
Swizzle<T, Dim, Packed, 1, 3, 1, 2> ywyz;
Swizzle<T, Dim, Packed, 1, 3, 1, 3> ywyw;
Swizzle<T, Dim, Packed, 1, 3, 2, 0> ywzx;
Swizzle<T, Dim, Packed, 1, 3, 2, 1> ywzy;
Swizzle<T, Dim, Packed, 1, 3, 2, 2> ywzz;
Swizzle<T, Dim, Packed, 1, 3, 2, 3> ywzw;
Swizzle<T, Dim, Packed, 1, 3, 3, 0> ywwx;
Swizzle<T, Dim, Packed, 1, 3, 3, 1> ywwy;
Swizzle<T, Dim, Packed, 1, 3, 3, 2> ywwz;
Swizzle<T, Dim, Packed, 1, 3, 3, 3> ywww;
Swizzle<T, Dim, Packed, 2, 0, 0, 0> zxxx;
Swizzle<T, Dim, Packed, 2, 0, 0, 1> zxxy;
Swizzle<T, Dim, Packed, 2, 0, 0, 2> zxxz;
Swizzle<T, Dim, Packed, 2, 0, 0, 3> zxxw;
Swizzle<T, Dim, Packed, 2, 0, 1, 0> zxyx;
Swizzle<T, Dim, Packed, 2, 0, 1, 1> zxyy;
Swizzle<T, Dim, Packed, 2, 0, 1, 2> zxyz;
Swizzle<T, Dim, Packed, 2, 0, 1, 3> zxyw;
Swizzle<T, Dim, Packed, 2, 0, 2, 0> zxzx;
Swizzle<T, Dim, Packed, 2, 0, 2, 1> zxzy;
Swizzle<T, Dim, Packed, 2, 0, 2, 2> zxzz;
Swizzle<T, Dim, Packed, 2, 0, 2, 3> zxzw;
Swizzle<T, Dim, Packed, 2, 0, 3, 0> zxwx;
Swizzle<T, Dim, Packed, 2, 0, 3, 1> zxwy;
Swizzle<T, Dim, Packed, 2, 0, 3, 2> zxwz;
Swizzle<T, Dim, Packed, 2, 0, 3, 3> zxww;
Swizzle<T, Dim, Packed, 2, 1, 0, 0> zyxx;
Swizzle<T, Dim, Packed, 2, 1, 0, 1> zyxy;
Swizzle<T, Dim, Packed, 2, 1, 0, 2> zyxz;
Swizzle<T, Dim, Packed, 2, 1, 0, 3> zyxw;
Swizzle<T, Dim, Packed, 2, 1, 1, 0> zyyx;
Swizzle<T, Dim, Packed, 2, 1, 1, 1> zyyy;
Swizzle<T, Dim, Packed, 2, 1, 1, 2> zyyz;
Swizzle<T, Dim, Packed, 2, 1, 1, 3> zyyw;
Swizzle<T, Dim, Packed, 2, 1, 2, 0> zyzx;
Swizzle<T, Dim, Packed, 2, 1, 2, 1> zyzy;
Swizzle<T, Dim, Packed, 2, 1, 2, 2> zyzz;
Swizzle<T, Dim, Packed, 2, 1, 2, 3> zyzw;
Swizzle<T, Dim, Packed, 2, 1, 3, 0> zywx;
Swizzle<T, Dim, Packed, 2, 1, 3, 1> zywy;
Swizzle<T, Dim, Packed, 2, 1, 3, 2> zywz;
Swizzle<T, Dim, Packed, 2, 1, 3, 3> zyww;
Swizzle<T, Dim, Packed, 2, 2, 0, 0> zzxx;
Swizzle<T, Dim, Packed, 2, 2, 0, 1> zzxy;
Swizzle<T, Dim, Packed, 2, 2, 0, 2> zzxz;
Swizzle<T, Dim, Packed, 2, 2, 0, 3> zzxw;
Swizzle<T, Dim, Packed, 2, 2, 1, 0> zzyx;
Swizzle<T, Dim, Packed, 2, 2, 1, 1> zzyy;
Swizzle<T, Dim, Packed, 2, 2, 1, 2> zzyz;
Swizzle<T, Dim, Packed, 2, 2, 1, 3> zzyw;
Swizzle<T, Dim, Packed, 2, 2, 2, 0> zzzx;
Swizzle<T, Dim, Packed, 2, 2, 2, 1> zzzy;
Swizzle<T, Dim, Packed, 2, 2, 2, 2> zzzz;
Swizzle<T, Dim, Packed, 2, 2, 2, 3> zzzw;
Swizzle<T, Dim, Packed, 2, 2, 3, 0> zzwx;
Swizzle<T, Dim, Packed, 2, 2, 3, 1> zzwy;
Swizzle<T, Dim, Packed, 2, 2, 3, 2> zzwz;
Swizzle<T, Dim, Packed, 2, 2, 3, 3> zzww;
Swizzle<T, Dim, Packed, 2, 3, 0, 0> zwxx;
Swizzle<T, Dim, Packed, 2, 3, 0, 1> zwxy;
Swizzle<T, Dim, Packed, 2, 3, 0, 2> zwxz;
Swizzle<T, Dim, Packed, 2, 3, 0, 3> zwxw;
Swizzle<T, Dim, Packed, 2, 3, 1, 0> zwyx;
Swizzle<T, Dim, Packed, 2, 3, 1, 1> zwyy;
Swizzle<T, Dim, Packed, 2, 3, 1, 2> zwyz;
Swizzle<T, Dim, Packed, 2, 3, 1, 3> zwyw;
Swizzle<T, Dim, Packed, 2, 3, 2, 0> zwzx;
Swizzle<T, Dim, Packed, 2, 3, 2, 1> zwzy;
Swizzle<T, Dim, Packed, 2, 3, 2, 2> zwzz;
Swizzle<T, Dim, Packed, 2, 3, 2, 3> zwzw;
Swizzle<T, Dim, Packed, 2, 3, 3, 0> zwwx;
Swizzle<T, Dim, Packed, 2, 3, 3, 1> zwwy;
Swizzle<T, Dim, Packed, 2, 3, 3, 2> zwwz;
Swizzle<T, Dim, Packed, 2, 3, 3, 3> zwww;
Swizzle<T, Dim, Packed, 3, 0, 0, 0> wxxx;
Swizzle<T, Dim, Packed, 3, 0, 0, 1> wxxy;
Swizzle<T, Dim, Packed, 3, 0, 0, 2> wxxz;
Swizzle<T, Dim, Packed, 3, 0, 0, 3> wxxw;
Swizzle<T, Dim, Packed, 3, 0, 1, 0> wxyx;
Swizzle<T, Dim, Packed, 3, 0, 1, 1> wxyy;
Swizzle<T, Dim, Packed, 3, 0, 1, 2> wxyz;
Swizzle<T, Dim, Packed, 3, 0, 1, 3> wxyw;
Swizzle<T, Dim, Packed, 3, 0, 2, 0> wxzx;
Swizzle<T, Dim, Packed, 3, 0, 2, 1> wxzy;
Swizzle<T, Dim, Packed, 3, 0, 2, 2> wxzz;
Swizzle<T, Dim, Packed, 3, 0, 2, 3> wxzw;
Swizzle<T, Dim, Packed, 3, 0, 3, 0> wxwx;
Swizzle<T, Dim, Packed, 3, 0, 3, 1> wxwy;
Swizzle<T, Dim, Packed, 3, 0, 3, 2> wxwz;
Swizzle<T, Dim, Packed, 3, 0, 3, 3> wxww;
Swizzle<T, Dim, Packed, 3, 1, 0, 0> wyxx;
Swizzle<T, Dim, Packed, 3, 1, 0, 1> wyxy;
Swizzle<T, Dim, Packed, 3, 1, 0, 2> wyxz;
Swizzle<T, Dim, Packed, 3, 1, 0, 3> wyxw;
Swizzle<T, Dim, Packed, 3, 1, 1, 0> wyyx;
Swizzle<T, Dim, Packed, 3, 1, 1, 1> wyyy;
Swizzle<T, Dim, Packed, 3, 1, 1, 2> wyyz;
Swizzle<T, Dim, Packed, 3, 1, 1, 3> wyyw;
Swizzle<T, Dim, Packed, 3, 1, 2, 0> wyzx;
Swizzle<T, Dim, Packed, 3, 1, 2, 1> wyzy;
Swizzle<T, Dim, Packed, 3, 1, 2, 2> wyzz;
Swizzle<T, Dim, Packed, 3, 1, 2, 3> wyzw;
Swizzle<T, Dim, Packed, 3, 1, 3, 0> wywx;
Swizzle<T, Dim, Packed, 3, 1, 3, 1> wywy;
Swizzle<T, Dim, Packed, 3, 1, 3, 2> wywz;
Swizzle<T, Dim, Packed, 3, 1, 3, 3> wyww;
Swizzle<T, Dim, Packed, 3, 2, 0, 0> wzxx;
Swizzle<T, Dim, Packed, 3, 2, 0, 1> wzxy;
Swizzle<T, Dim, Packed, 3, 2, 0, 2> wzxz;
Swizzle<T, Dim, Packed, 3, 2, 0, 3> wzxw;
Swizzle<T, Dim, Packed, 3, 2, 1, 0> wzyx;
Swizzle<T, Dim, Packed, 3, 2, 1, 1> wzyy;
Swizzle<T, Dim, Packed, 3, 2, 1, 2> wzyz;
Swizzle<T, Dim, Packed, 3, 2, 1, 3> wzyw;
Swizzle<T, Dim, Packed, 3, 2, 2, 0> wzzx;
Swizzle<T, Dim, Packed, 3, 2, 2, 1> wzzy;
Swizzle<T, Dim, Packed, 3, 2, 2, 2> wzzz;
Swizzle<T, Dim, Packed, 3, 2, 2, 3> wzzw;
Swizzle<T, Dim, Packed, 3, 2, 3, 0> wzwx;
Swizzle<T, Dim, Packed, 3, 2, 3, 1> wzwy;
Swizzle<T, Dim, Packed, 3, 2, 3, 2> wzwz;
Swizzle<T, Dim, Packed, 3, 2, 3, 3> wzww;
Swizzle<T, Dim, Packed, 3, 3, 0, 0> wwxx;
Swizzle<T, Dim, Packed, 3, 3, 0, 1> wwxy;
Swizzle<T, Dim, Packed, 3, 3, 0, 2> wwxz;
Swizzle<T, Dim, Packed, 3, 3, 0, 3> wwxw;
Swizzle<T, Dim, Packed, 3, 3, 1, 0> wwyx;
Swizzle<T, Dim, Packed, 3, 3, 1, 1> wwyy;
Swizzle<T, Dim, Packed, 3, 3, 1, 2> wwyz;
Swizzle<T, Dim, Packed, 3, 3, 1, 3> wwyw;
Swizzle<T, Dim, Packed, 3, 3, 2, 0> wwzx;
Swizzle<T, Dim, Packed, 3, 3, 2, 1> wwzy;
Swizzle<T, Dim, Packed, 3, 3, 2, 2> wwzz;
Swizzle<T, Dim, Packed, 3, 3, 2, 3> wwzw;
Swizzle<T, Dim, Packed, 3, 3, 3, 0> wwwx;
Swizzle<T, Dim, Packed, 3, 3, 3, 1> wwwy;
Swizzle<T, Dim, Packed, 3, 3, 3, 2> wwwz;
Swizzle<T, Dim, Packed, 3, 3, 3, 3> wwww;
