Swizzle<T, Dim, Packed, 0, 0> xx;
Swizzle<T, Dim, Packed, 0, 1> xy;
Swizzle<T, Dim, Packed, 1, 0> yx;
Swizzle<T, Dim, Packed, 1, 1> yy;
Swizzle<T, Dim, Packed, 0, 0, 0> xxx;
Swizzle<T, Dim, Packed, 0, 0, 1> xxy;
Swizzle<T, Dim, Packed, 0, 1, 0> xyx;
Swizzle<T, Dim, Packed, 0, 1, 1> xyy;
Swizzle<T, Dim, Packed, 1, 0, 0> yxx;
Swizzle<T, Dim, Packed, 1, 0, 1> yxy;
Swizzle<T, Dim, Packed, 1, 1, 0> yyx;
Swizzle<T, Dim, Packed, 1, 1, 1> yyy;
Swizzle<T, Dim, Packed, 0, 0, 0, 0> xxxx;
Swizzle<T, Dim, Packed, 0, 0, 0, 1> xxxy;
Swizzle<T, Dim, Packed, 0, 0, 1, 0> xxyx;
Swizzle<T, Dim, Packed, 0, 0, 1, 1> xxyy;
Swizzle<T, Dim, Packed, 0, 1, 0, 0> xyxx;
Swizzle<T, Dim, Packed, 0, 1, 0, 1> xyxy;
Swizzle<T, Dim, Packed, 0, 1, 1, 0> xyyx;
Swizzle<T, Dim, Packed, 0, 1, 1, 1> xyyy;
Swizzle<T, Dim, Packed, 1, 0, 0, 0> yxxx;
Swizzle<T, Dim, Packed, 1, 0, 0, 1> yxxy;
Swizzle<T, Dim, Packed, 1, 0, 1, 0> yxyx;
Swizzle<T, Dim, Packed, 1, 0, 1, 1> yxyy;
Swizzle<T, Dim, Packed, 1, 1, 0, 0> yyxx;
Swizzle<T, Dim, Packed, 1, 1, 0, 1> yyxy;
Swizzle<T, Dim, Packed, 1, 1, 1, 0> yyyx;
Swizzle<T, Dim, Packed, 1, 1, 1, 1> yyyy;
